// <auto-generated />
using System;
using CourseProjectYacenko.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CourseProjectYacenko.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251226093615_121123")]
    partial class _121123
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CourseProjectYacenko.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PassportData")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "г. Москва, ул. Административная, д. 1",
                            Balance = 10000.00m,
                            Email = "admin@mobileoperator.ru",
                            FullName = "Администратор Системы",
                            IsActive = true,
                            PassportData = "0000 000000",
                            PasswordHash = "$2a$11$Tfcrs4EXGULPoK6KkadmNu2sykiVqRDWdXzC1z9zBILc0psbGHToy",
                            PhoneNumber = "+79998887766",
                            RegistrationDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("CourseProjectYacenko.Models.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProcessingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("CourseProjectYacenko.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("CourseProjectYacenko.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BillingPeriod")
                        .HasColumnType("int");

                    b.Property<decimal>("Cost")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("TariffId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TariffId");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BillingPeriod = 2,
                            Cost = 50.00m,
                            Description = "Безлимитный YouTube",
                            Name = "YouTube безлимит",
                            Type = 3
                        },
                        new
                        {
                            Id = 2,
                            BillingPeriod = 2,
                            Cost = 100.00m,
                            Description = "Защита устройства",
                            Name = "Антивирус",
                            Type = 4
                        },
                        new
                        {
                            Id = 3,
                            BillingPeriod = 2,
                            Cost = 30.00m,
                            Description = "Безлимитная музыка",
                            Name = "Музыка",
                            Type = 3
                        });
                });

            modelBuilder.Entity("CourseProjectYacenko.Models.Tariff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AppUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("InternetTrafficGB")
                        .HasColumnType("int");

                    b.Property<int>("MinutesCount")
                        .HasColumnType("int");

                    b.Property<decimal>("MonthlyFee")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SmsCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("Tariffs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Для новых клиентов",
                            InternetTrafficGB = 5,
                            MinutesCount = 100,
                            MonthlyFee = 300.00m,
                            Name = "Базовый",
                            SmsCount = 50
                        },
                        new
                        {
                            Id = 2,
                            Description = "Популярный тариф",
                            InternetTrafficGB = 15,
                            MinutesCount = 300,
                            MonthlyFee = 500.00m,
                            Name = "Стандарт",
                            SmsCount = 100
                        },
                        new
                        {
                            Id = 3,
                            Description = "Для активных пользователей",
                            InternetTrafficGB = 30,
                            MinutesCount = 1000,
                            MonthlyFee = 1000.00m,
                            Name = "Премиум",
                            SmsCount = 500
                        });
                });

            modelBuilder.Entity("CourseProjectYacenko.Models.Application", b =>
                {
                    b.HasOne("CourseProjectYacenko.Models.AppUser", "AppUser")
                        .WithMany("Applications")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("CourseProjectYacenko.Models.Payment", b =>
                {
                    b.HasOne("CourseProjectYacenko.Models.AppUser", "AppUser")
                        .WithMany("Payments")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("CourseProjectYacenko.Models.Service", b =>
                {
                    b.HasOne("CourseProjectYacenko.Models.Tariff", "Tariff")
                        .WithMany("ConnectedServices")
                        .HasForeignKey("TariffId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Tariff");
                });

            modelBuilder.Entity("CourseProjectYacenko.Models.Tariff", b =>
                {
                    b.HasOne("CourseProjectYacenko.Models.AppUser", "AppUser")
                        .WithMany("Tariffs")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("CourseProjectYacenko.Models.AppUser", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("Payments");

                    b.Navigation("Tariffs");
                });

            modelBuilder.Entity("CourseProjectYacenko.Models.Tariff", b =>
                {
                    b.Navigation("ConnectedServices");
                });
#pragma warning restore 612, 618
        }
    }
}
