// <auto-generated />
using System;
using CourseProjectYacenko.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CourseProjectYacenko.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CourseProjectYacenko.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PassportData")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "г. Москва, ул. Административная, д. 1",
                            Balance = 10000.00m,
                            Email = "admin@mobileoperator.ru",
                            FullName = "Администратор Системы",
                            IsActive = true,
                            PassportData = "0000 000000",
                            PasswordHash = "$2a$11$XMcVtQQ3bQwNX2lozQfoyOyreHMPifSuS/.sOxqpUzm6co9q69vQ6",
                            PhoneNumber = "9998887766",
                            RegistrationDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Address = "г. Москва, ул. Примерная, д. 10",
                            Balance = 1500.50m,
                            Email = "ivanov@example.com",
                            FullName = "Иванов Иван Иванович",
                            IsActive = true,
                            PassportData = "1234 567890",
                            PasswordHash = "$2a$11$PTdbwEfGpJOE5dTidkUeUOljftB1L2p1E1voVh5DkSco9VNpOiw7O",
                            PhoneNumber = "9991112233",
                            RegistrationDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Role = "User"
                        },
                        new
                        {
                            Id = 3,
                            Address = "г. Санкт-Петербург, ул. Тестовая, д. 5",
                            Balance = 750.25m,
                            Email = "petrova@example.com",
                            FullName = "Петрова Анна Сергеевна",
                            IsActive = true,
                            PassportData = "5678 901234",
                            PasswordHash = "$2a$11$QWM.SQuD6Jb1GZhF6g55bO9UyzKrAtbCAe6oqVCvfmr/LR9rJxfuC",
                            PhoneNumber = "9992223344",
                            RegistrationDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Role = "User"
                        });
                });

            modelBuilder.Entity("CourseProjectYacenko.Models.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProcessingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("Applications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppUserId = 2,
                            Comment = "Новое подключение обработано",
                            CreationDate = new DateTime(2024, 2, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            ProcessingDate = new DateTime(2024, 2, 2, 14, 30, 0, 0, DateTimeKind.Utc),
                            Status = 2,
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            AppUserId = 3,
                            Comment = "Запрос на смену тарифа",
                            CreationDate = new DateTime(2024, 3, 5, 11, 20, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            Type = 1
                        });
                });

            modelBuilder.Entity("CourseProjectYacenko.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 1000.00m,
                            AppUserId = 2,
                            PaymentDateTime = new DateTime(2024, 2, 5, 10, 30, 0, 0, DateTimeKind.Utc),
                            PaymentMethod = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 500.50m,
                            AppUserId = 2,
                            PaymentDateTime = new DateTime(2024, 3, 10, 14, 15, 0, 0, DateTimeKind.Utc),
                            PaymentMethod = 3,
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            Amount = 1000.00m,
                            AppUserId = 3,
                            PaymentDateTime = new DateTime(2024, 3, 15, 9, 45, 0, 0, DateTimeKind.Utc),
                            PaymentMethod = 1,
                            Status = 1
                        });
                });

            modelBuilder.Entity("CourseProjectYacenko.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BillingPeriod")
                        .HasColumnType("int");

                    b.Property<decimal>("Cost")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("TariffId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TariffId");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BillingPeriod = 2,
                            Cost = 50.00m,
                            Description = "Безлимитный YouTube",
                            Name = "YouTube безлимит",
                            Type = 3
                        },
                        new
                        {
                            Id = 2,
                            BillingPeriod = 2,
                            Cost = 100.00m,
                            Description = "Защита устройства",
                            Name = "Антивирус",
                            Type = 4
                        },
                        new
                        {
                            Id = 3,
                            BillingPeriod = 2,
                            Cost = 30.00m,
                            Description = "Безлимитная музыка",
                            Name = "Музыка",
                            Type = 3
                        },
                        new
                        {
                            Id = 4,
                            BillingPeriod = 2,
                            Cost = 80.00m,
                            Description = "Звонки за границу",
                            Name = "Международные звонки",
                            Type = 1
                        });
                });

            modelBuilder.Entity("CourseProjectYacenko.Models.Tariff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AppUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("InternetTrafficGB")
                        .HasColumnType("int");

                    b.Property<int>("MinutesCount")
                        .HasColumnType("int");

                    b.Property<decimal>("MonthlyFee")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SmsCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("Tariffs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Для новых клиентов",
                            InternetTrafficGB = 5,
                            MinutesCount = 100,
                            MonthlyFee = 300.00m,
                            Name = "Базовый",
                            SmsCount = 50
                        },
                        new
                        {
                            Id = 2,
                            Description = "Популярный тариф",
                            InternetTrafficGB = 15,
                            MinutesCount = 300,
                            MonthlyFee = 500.00m,
                            Name = "Стандарт",
                            SmsCount = 100
                        },
                        new
                        {
                            Id = 3,
                            Description = "Для активных пользователей",
                            InternetTrafficGB = 30,
                            MinutesCount = 1000,
                            MonthlyFee = 1000.00m,
                            Name = "Премиум",
                            SmsCount = 500
                        },
                        new
                        {
                            Id = 4,
                            Description = "Минимальный пакет",
                            InternetTrafficGB = 2,
                            MinutesCount = 50,
                            MonthlyFee = 200.00m,
                            Name = "Эконом",
                            SmsCount = 20
                        });
                });

            modelBuilder.Entity("CourseProjectYacenko.Models.Application", b =>
                {
                    b.HasOne("CourseProjectYacenko.Models.AppUser", "AppUser")
                        .WithMany("Applications")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("CourseProjectYacenko.Models.Payment", b =>
                {
                    b.HasOne("CourseProjectYacenko.Models.AppUser", "AppUser")
                        .WithMany("Payments")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("CourseProjectYacenko.Models.Service", b =>
                {
                    b.HasOne("CourseProjectYacenko.Models.Tariff", "Tariff")
                        .WithMany("ConnectedServices")
                        .HasForeignKey("TariffId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Tariff");
                });

            modelBuilder.Entity("CourseProjectYacenko.Models.Tariff", b =>
                {
                    b.HasOne("CourseProjectYacenko.Models.AppUser", "AppUser")
                        .WithMany("Tariffs")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("CourseProjectYacenko.Models.AppUser", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("Payments");

                    b.Navigation("Tariffs");
                });

            modelBuilder.Entity("CourseProjectYacenko.Models.Tariff", b =>
                {
                    b.Navigation("ConnectedServices");
                });
#pragma warning restore 612, 618
        }
    }
}
